app:
  address: ':5300'
  mode: prod
  tz: Asia/Shanghai
  printStack: false

database:
  dsn: "host=localhost user= dbname=chatpuppy port=5432 sslmode=disable"
  debug: false

redis:
  address: 'localhost:6379'
  password: ''
  db: 3
