basePath: /
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  model.GroupCreateReq:
    properties:
      category:
        description: group's category
        type: string
      intro:
        description: group intro
        type: string
      maxMembers:
        description: group's max members
        type: integer
      name:
        maxLength: 20
        minLength: 2
        type: string
      public:
        description: '`true` create public group, `false` create private group'
        type: boolean
      sharedPublic:
        description: Member's public key for `ecdh` exchange
        type: string
    required:
    - category
    - name
    - sharedPublic
    type: object
  model.GroupDetailWithPublicKey:
    properties:
      address:
        type: string
      category:
        type: string
      groupPublicKey:
        type: string
      intro:
        type: string
      keyId:
        type: string
      membersMax:
        type: integer
      name:
        type: string
      owner:
        description: group is belongs to current member
        type: boolean
      public:
        description: group is public or private
        type: boolean
    type: object
  model.GroupJoinReq:
    properties:
      groupId:
        type: string
      sharedPublic:
        description: Member's public key for `ecdh` exchange
        type: string
    required:
    - groupId
    - sharedPublic
    type: object
  model.MemberNonceRes:
    properties:
      nonce:
        type: string
    type: object
  model.MemberProfile:
    properties:
      address:
        type: string
      avatar:
        description: optional
        type: string
      intro:
        description: optional
        type: string
      nickname:
        description: optional
        type: string
    type: object
  model.MemberSigninRes:
    properties:
      profile:
        allOf:
        - $ref: '#/definitions/model.MemberProfile'
      token:
        type: string
    type: object
info:
  contact: {}
  description: |+
    # ChatPuppy Api Document

    ## Auth
    - Add headers `Authorization Bearer {token}`
    - Add headers `X-Member-Address ${address}`

    ## Signature
    1. Just post request
    2. Encrypt raw post body string to `MD5`, getting string `bodyMD5`
    3. Concatenate `timestamp` (from 1970, 10 digits) string end of step 2, getting string `s = bodyMD5 + timestamp`
    4. Sign `s` getting `signature` string
    5. Add headers `X-Signature ${signature}`
    6. Add headers `X-Timestamp ${timestamp}`

  title: ChatPuppy Api Doc
  version: "1.0"
paths:
  /group:
    post:
      consumes:
      - application/json
      description: create an group (need signature verify)
      operationId: GroupCreate
      parameters:
      - description: Group info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.GroupDetailWithPublicKey'
              type: object
      summary: Group Create
      tags:
      - Group
  /group/join:
    post:
      consumes:
      - application/json
      operationId: GroupJoin
      parameters:
      - description: Join info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupJoinReq'
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.GroupDetailWithPublicKey'
              type: object
      summary: Join Group
      tags:
      - Group
  /member/{address}:
    get:
      consumes:
      - application/json
      description: Getting member's profile using address
      operationId: MemberProfile
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            $ref: '#/definitions/app.Response'
      summary: Member Profile
      tags:
      - Member
  /member/nonce/{address}:
    get:
      consumes:
      - application/json
      description: Getting nonce string to be signed
      operationId: MemberNonce
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.MemberNonceRes'
              type: object
      summary: Member Signin Nonce
      tags:
      - Member
  /memeber:
    post:
      consumes:
      - application/json
      operationId: MemberSignin
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.MemberSigninRes'
              type: object
      summary: Member Signin
      tags:
      - Member
swagger: "2.0"
